name: Build and deploy to GitHub Pages

on:
  push:
    branches: ["main", "rc"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Install Zola
      uses: taiki-e/install-action@v2
      with:
        tool: zola@0.22.0

    - name: Install Cranko
      run: |
        set -xeuo pipefail
        d="$(mktemp -d /tmp/cranko.XXXXXX)"
        cd "$d"
        curl --proto '=https' --tlsv1.2 -sSf https://pkgw.github.io/cranko/fetch-latest.sh |sh
        echo "$d" >>"$GITHUB_PATH"

    - name: Apply versions with Cranko
      run: cranko release-workflow apply-versions

    # Cranko is strict and doesn't want to see ZENODO_TOKEN set except on RC
    # builds, but GitHub Actions will expose it on trusted pull requests and
    # main-branch builds. This is the best way I can figure out how to limit
    # its exposure to make Cranko happy:
    - name: Maybe expose ZENODO_TOKEN
      if: ${{ github.ref_name == 'rc' }}
      run: 'echo "ZENODO_TOKEN=${ZENODO_TOKEN}" >>"${GITHUB_ENV}"'
      env:
        ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}

    - name: Preregister Zenodo DOI
      run: |
        cranko zenodo preregister --metadata=zenodo.json5 onegoodtutorial CHANGELOG.md content/about.md

    - name: Generate release commit repo bundle
      run: |
        set -xeuo pipefail
        git add .
        cranko release-workflow commit
        git show
        git bundle create onegoodtutorial-source.bundle --all

    - name: Generate source Zip for Zenodo
      run: git archive --format=zip --output=onegoodtutorial-source.zip HEAD

    - name: Build site
      run: zola build

    - name: Upload built site as Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public

    - name: Upload built site as regular artifact
      uses: actions/upload-artifact@v4
      with:
        name: onegoodtutorial-built.zip
        path: ./public

    - name: Upload repo bundle artifact
      uses: actions/upload-artifact@v4
      with:
        name: onegoodtutorial-source.bundle
        path: onegoodtutorial-source.bundle

    - name: Upload source Zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: onegoodtutorial-source.zip
        path: onegoodtutorial-source.zip

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref_name == 'rc' }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  make-release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref_name == 'rc' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install Cranko
      run: |
        set -xeuo pipefail
        d="$(mktemp -d /tmp/cranko.XXXXXX)"
        cd "$d"
        curl --proto '=https' --tlsv1.2 -sSf https://pkgw.github.io/cranko/fetch-latest.sh |sh
        echo "$d" >>"$GITHUB_PATH"

    - name: Retrieve artifacts
      uses: actions/download-artifact@v5

    - name: TEMP ARTIFACT DEBUG
      run: find -type f |sort

    - name: Restore release commit
      run: |
        set -xeuo pipefail
        git switch -c release
        git pull --ff-only onegoodtutorial-source.bundle

    - name: Retrieve and apply project version
      run: |
        set -xeuo pipefail
        v=$(cranko show version)
        mv onegoodtutorial-source.bundle onegoodtutorial-${v}-source.bundle
        mv onegoodtutorial-source.zip onegoodtutorial-${v}-source.zip
        mv onegoodtutorial-built.zip onegoodtutorial-${v}-built.zip

    - name: Tag and push
      run: |
        set -xeuo pipefail
        cranko release-workflow tag
        git push --tags origin release:release

    - name: Create GitHub releases
      run: cranko github create-releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Zenodo artifacts
      run: cranko zenodo upload-artifacts --metadata=zenodo.json5 onegoodtutorial-*-built.zip onegoodtutorial-*-source.*
      env:
        ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}

    - name: Publish to Zenodo
      run: cranko zenodo publish --metadata=zenodo.json5
      env:
        ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}

  TEMP-ARTIFACT-DEBUG:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Retrieve artifacts
      uses: actions/download-artifact@v5

    - name: TEMP ARTIFACT DEBUG
      run: find -type f |sort
